[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "yfinance",
    "pandas",
    "python-decouple",
    "SQLAlchemy",
    "pydantic-settings",
    "pydantic[email]",
    "passlib[bcrypt]",
    "python-jose[cryptography]",
]

[tool.setuptools]
packages = ["app"]
